name: package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y wine-stable wine32 >/dev/null 2>&1
          wineboot >/dev/null 2>&1

      - name: Package
        run: |
          set -xeu -o pipefail
          ./extra/package.sh

      - name: Upload artifacts - dat
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          path: translations/*.dat

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            translations/*.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
